#:schema https://mise.en.dev/schema/mise.json

[tools]
uv = "latest"
bun = "latest"
node = "latest"
just = "latest"
ruff = "latest"
shfmt = "latest"
usage = "latest"
tombi = "latest"
oxfmt = "latest"
python = "latest"
oxlint = "latest"
pitchfork = "latest"
shellcheck = "latest"
# pipecat cloud auth whoami
"pipx:pipecat-ai-cli" = { version = "latest" }
"github:facebook/pyrefly" = "latest"
"github:bensadeh/tailspin" = "latest"
# lk cloud auth
# search docs: lk docs search "<search-string>"
"github:livekit/livekit-cli" = "latest"
#
# dg login
# https://developers.deepgram.com/developer-tools/cli/getting-started
"pipx:deepgram/cli" = "latest"

[env]
# strictly ensures `uv` uses `mise`'s managed Python interpreter
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }

[settings]
pipx.uvx = true
experimental = true
python.uv_venv_auto = "source"
idiomatic_version_file_enable_tools = ["node", "bun"]
